// frontend/app/employees/page.tsx
'use client'

import { useState, useEffect, useMemo } from 'react'
import Link from 'next/link'
import {
  Plus,
  Edit,
  User,
  Users,
  Building,
  ChevronDown,
  ChevronRight,
  LayoutGrid,
  GitBranch,
  List,
  Mail,
  Phone
} from 'lucide-react'

import { API_URL } from '@/lib/config'
import { useAuth } from '@/lib/auth'

interface Employee {
  id: string
  name: string
  position: string
  email: string | null
  department: string | null
  manager_id: string | null
  phone: string | null
  mobile: string | null
  photo_base64: string | null
  meeting_frequency: string
  meeting_day: string | null
  development_priorities: string | null
  level?: number
}

type ViewMode = 'tiles' | 'tree' | 'list'
type FilterMode = 'my-team' | 'all'

export default function EmployeesPage() {
  const { user, subordinates: authSubordinates } = useAuth()
  const [allEmployees, setAllEmployees] = useState<Employee[]>([])
  const [loading, setLoading] = useState(true)
  const [showModal, setShowModal] = useState(false)
  const [editingEmployee, setEditingEmployee] = useState<Employee | null>(null)
  const [filter, setFilter] = useState<FilterMode>('my-team')
  const [viewMode, setViewMode] = useState<ViewMode>('tree')
  const [expandedDepts, setExpandedDepts] = useState<Set<string>>(new Set())
  const [expandedNodes, setExpandedNodes] = useState<Set<string>>(new Set())
  const [formData, setFormData] = useState({
    name: '',
    position: '',
    meeting_frequency: 'weekly',
    meeting_day: '',
    development_priorities: '',
  })

  // Fetch all employees once
  useEffect(() => {
    fetchAllEmployees()
  }, [])

  // Set expanded nodes when employees change
  useEffect(() => {
    if (employees.length > 0) {
      // Find root nodes and expand them by default
      const roots = employees.filter(emp =>
        !emp.manager_id || !employees.some(e => e.id === emp.manager_id)
      )
      const rootIds = new Set(roots.map(r => r.id))
      setExpandedNodes(rootIds)
    }
  }, [filter, allEmployees, authSubordinates])

  const fetchAllEmployees = async () => {
    setLoading(true)
    try {
      const res = await fetch(`${API_URL}/employees`)
      if (res.ok) {
        const data = await res.json()
        setAllEmployees(data)
      }
    } catch (error) {
      console.error('Failed to fetch employees:', error)
    } finally {
      setLoading(false)
    }
  }

  // Filter employees based on mode
  const employees = useMemo(() => {
    if (filter === 'all') {
      // Show all employees with departments only
      return allEmployees.filter(emp => emp.department)
    }
    // For 'my-team', use subordinates from auth context
    // Filter to only show employees with departments
    if (authSubordinates.length > 0) {
      const subordinateIds = new Set(authSubordinates.map(s => s.id))
      return allEmployees.filter(emp =>
        emp.department && (subordinateIds.has(emp.id) || (user && emp.id === user.id))
      )
    }
    return []
  }, [filter, allEmployees, authSubordinates, user])

  // Build org tree structure
  const orgTree = useMemo(() => {
    const employeeMap = new Map(employees.map(e => [e.id, e]))
    const children = new Map<string | null, Employee[]>()

    employees.forEach(emp => {
      const managerId = emp.manager_id
      if (!children.has(managerId)) {
        children.set(managerId, [])
      }
      children.get(managerId)!.push(emp)
    })

    // Find root employees (no manager or manager not in filtered list)
    const roots = employees.filter(emp =>
      !emp.manager_id || !employeeMap.has(emp.manager_id)
    )

    // Sort roots by name
    roots.sort((a, b) => a.name.localeCompare(b.name))

    return { roots, children, employeeMap }
  }, [employees])

  // Group by department
  const groupedByDepartment = useMemo(() => {
    const groups: Record<string, Employee[]> = {}
    employees.forEach(emp => {
      const dept = emp.department || 'Без отдела'
      if (!groups[dept]) groups[dept] = []
      groups[dept].push(emp)
    })
    // Sort departments
    return Object.fromEntries(
      Object.entries(groups).sort(([a], [b]) => a.localeCompare(b))
    )
  }, [employees])

  // Count direct subordinates for an employee
  const getSubordinateCount = (employeeId: string): number => {
    return orgTree.children.get(employeeId)?.length || 0
  }

  const toggleDept = (dept: string) => {
    const newExpanded = new Set(expandedDepts)
    if (newExpanded.has(dept)) {
      newExpanded.delete(dept)
    } else {
      newExpanded.add(dept)
    }
    setExpandedDepts(newExpanded)
  }

  const toggleNode = (id: string) => {
    const newExpanded = new Set(expandedNodes)
    if (newExpanded.has(id)) {
      newExpanded.delete(id)
    } else {
      newExpanded.add(id)
    }
    setExpandedNodes(newExpanded)
  }

  const openModal = (employee?: Employee) => {
    if (employee) {
      setEditingEmployee(employee)
      setFormData({
        name: employee.name,
        position: employee.position,
        meeting_frequency: employee.meeting_frequency,
        meeting_day: employee.meeting_day || '',
        development_priorities: employee.development_priorities || '',
      })
    } else {
      setEditingEmployee(null)
      setFormData({
        name: '',
        position: '',
        meeting_frequency: 'weekly',
        meeting_day: '',
        development_priorities: '',
      })
    }
    setShowModal(true)
  }

  const closeModal = () => {
    setShowModal(false)
    setEditingEmployee(null)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      const url = editingEmployee
        ? `${API_URL}/employees/${editingEmployee.id}`
        : `${API_URL}/employees`

      const res = await fetch(url, {
        method: editingEmployee ? 'PUT' : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      })

      if (res.ok) {
        await fetchAllEmployees()
        closeModal()
      }
    } catch (error) {
      console.error('Failed to save employee:', error)
    }
  }

  // Render tree node recursively
  const renderTreeNode = (employee: Employee, depth: number = 0) => {
    const children = orgTree.children.get(employee.id) || []
    const hasChildren = children.length > 0
    const isExpanded = expandedNodes.has(employee.id)

    return (
      <div key={employee.id} className="select-none">
        <div
          className={`group flex items-center gap-2 py-2 px-3 rounded-lg hover:bg-gray-50 cursor-pointer transition-colors ${
            depth === 0 ? 'bg-primary-50' : ''
          }`}
          style={{ marginLeft: depth * 24 }}
          onClick={() => hasChildren && toggleNode(employee.id)}
        >
          {/* Expand/collapse button */}
          <button
            className={`p-0.5 rounded ${hasChildren ? 'hover:bg-gray-200' : 'invisible'}`}
          >
            {isExpanded ? (
              <ChevronDown size={16} className="text-ekf-gray" />
            ) : (
              <ChevronRight size={16} className="text-ekf-gray" />
            )}
          </button>

          {/* Avatar */}
          <div className="w-10 h-10 bg-gray-200 rounded-full flex items-center justify-center flex-shrink-0 overflow-hidden">
            {employee.photo_base64 ? (
              <img
                src={`data:image/jpeg;base64,${employee.photo_base64}`}
                alt=""
                className="w-full h-full object-cover"
              />
            ) : (
              <User size={20} className="text-ekf-gray" />
            )}
          </div>

          {/* Info */}
          <Link
            href={`/employees/${employee.id}`}
            className="flex-1 min-w-0"
            onClick={(e) => e.stopPropagation()}
          >
            <p className="font-medium text-sm text-ekf-dark truncate hover:text-ekf-orange">
              {employee.name}
            </p>
            <p className="text-xs text-ekf-gray truncate">{employee.position}</p>
          </Link>

          {/* Subordinates count */}
          {hasChildren && (
            <span className="text-xs text-ekf-gray bg-gray-100 px-2 py-0.5 rounded">
              {children.length}
            </span>
          )}

          {/* Edit button */}
          <button
            onClick={(e) => {
              e.stopPropagation()
              openModal(employee)
            }}
            className="p-1.5 text-ekf-gray-light hover:text-ekf-orange hover:bg-primary-50 rounded opacity-0 group-hover:opacity-100 transition-opacity"
          >
            <Edit size={14} />
          </button>
        </div>

        {/* Children */}
        {isExpanded && hasChildren && (
          <div className="border-l-2 border-gray-200 ml-6">
            {children
              .sort((a, b) => a.name.localeCompare(b.name))
              .map(child => renderTreeNode(child, depth + 1))}
          </div>
        )}
      </div>
    )
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-ekf-orange"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div className="flex items-center gap-4">
          <h1 className="text-2xl font-bold text-ekf-dark">Команда</h1>

          {/* Filter toggle */}
          {user && (
            <div className="flex border border-gray-200 rounded-lg overflow-hidden">
              <button
                onClick={() => setFilter('my-team')}
                className={`flex items-center gap-1.5 px-4 py-2 text-sm font-medium transition-colors ${
                  filter === 'my-team'
                    ? 'bg-ekf-orange text-white'
                    : 'bg-white text-ekf-dark hover:bg-gray-50'
                }`}
              >
                <Users size={16} />
                Мои
              </button>
              <button
                onClick={() => setFilter('all')}
                className={`flex items-center gap-1.5 px-4 py-2 text-sm font-medium transition-colors ${
                  filter === 'all'
                    ? 'bg-ekf-orange text-white'
                    : 'bg-white text-ekf-dark hover:bg-gray-50'
                }`}
              >
                <Building size={16} />
                Все
              </button>
            </div>
          )}

          {/* View mode toggle */}
          <div className="flex border border-gray-200 rounded-lg overflow-hidden">
            <button
              onClick={() => setViewMode('tree')}
              className={`p-2 transition-colors ${
                viewMode === 'tree'
                  ? 'bg-ekf-orange text-white'
                  : 'bg-white text-ekf-dark hover:bg-gray-50'
              }`}
              title="Оргструктура"
            >
              <GitBranch size={18} />
            </button>
            <button
              onClick={() => setViewMode('tiles')}
              className={`p-2 transition-colors ${
                viewMode === 'tiles'
                  ? 'bg-ekf-orange text-white'
                  : 'bg-white text-ekf-dark hover:bg-gray-50'
              }`}
              title="Плитки"
            >
              <LayoutGrid size={18} />
            </button>
            <button
              onClick={() => setViewMode('list')}
              className={`p-2 transition-colors ${
                viewMode === 'list'
                  ? 'bg-ekf-orange text-white'
                  : 'bg-white text-ekf-dark hover:bg-gray-50'
              }`}
              title="Список"
            >
              <List size={18} />
            </button>
          </div>
        </div>

        <button
          onClick={() => openModal()}
          className="flex items-center gap-2 px-4 py-2 bg-ekf-orange text-white rounded-lg hover:bg-ekf-orange-dark transition-colors"
        >
          <Plus size={20} />
          Добавить
        </button>
      </div>

      {/* Stats */}
      <div className="bg-primary-50 border border-primary-100 rounded-lg p-4">
        <div className="flex items-center gap-2 text-ekf-orange">
          <Users size={20} />
          <span className="font-medium">{employees.length} сотрудников</span>
          {filter === 'my-team' && user && (
            <span className="text-ekf-gray">в вашем подчинении</span>
          )}
        </div>
      </div>

      {employees.length === 0 ? (
        <div className="bg-white rounded-lg shadow-sm border p-12 text-center">
          <User size={48} className="mx-auto text-ekf-gray-light mb-4" />
          <p className="text-ekf-gray mb-4">
            {filter === 'my-team' ? 'У вас нет подчинённых' : 'Пока нет сотрудников'}
          </p>
          {filter === 'my-team' && (
            <button
              onClick={() => setFilter('all')}
              className="text-ekf-orange hover:underline"
            >
              Показать всех сотрудников
            </button>
          )}
        </div>
      ) : (
        <>
          {/* Tree View */}
          {viewMode === 'tree' && (
            <div className="bg-white rounded-lg shadow-sm border p-4">
              <div className="space-y-1">
                {orgTree.roots.map(root => renderTreeNode(root, 0))}
              </div>
            </div>
          )}

          {/* Tiles View */}
          {viewMode === 'tiles' && (
            <div className="space-y-4">
              {Object.entries(groupedByDepartment).map(([dept, deptEmployees]) => (
                <div key={dept} className="bg-white rounded-lg shadow-sm border overflow-hidden">
                  <button
                    onClick={() => toggleDept(dept)}
                    className="flex items-center gap-2 w-full px-4 py-3 bg-gray-50 hover:bg-gray-100 transition-colors"
                  >
                    {expandedDepts.has(dept) ? (
                      <ChevronDown size={18} className="text-ekf-gray" />
                    ) : (
                      <ChevronRight size={18} className="text-ekf-gray" />
                    )}
                    <Building size={16} className="text-ekf-orange" />
                    <span className="font-medium text-ekf-dark">{dept}</span>
                    <span className="text-sm text-ekf-gray ml-auto">{deptEmployees.length} чел.</span>
                  </button>

                  {expandedDepts.has(dept) && (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4">
                      {deptEmployees.map((employee) => (
                        <div
                          key={employee.id}
                          className="bg-gray-50 rounded-lg p-4 hover:shadow-md transition-shadow border border-gray-100"
                        >
                          <div className="flex items-start gap-3">
                            <div className="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center flex-shrink-0 overflow-hidden">
                              {employee.photo_base64 ? (
                                <img
                                  src={`data:image/jpeg;base64,${employee.photo_base64}`}
                                  alt=""
                                  className="w-full h-full object-cover"
                                />
                              ) : (
                                <User size={24} className="text-ekf-gray" />
                              )}
                            </div>
                            <div className="flex-1 min-w-0">
                              <h3 className="font-semibold text-ekf-dark truncate">{employee.name}</h3>
                              <p className="text-sm text-ekf-gray truncate">{employee.position}</p>
                              {employee.email && (
                                <p className="text-xs text-ekf-gray-light truncate">{employee.email}</p>
                              )}
                            </div>
                            <button
                              onClick={() => openModal(employee)}
                              className="p-1 text-ekf-gray-light hover:text-ekf-orange"
                            >
                              <Edit size={14} />
                            </button>
                          </div>
                          <div className="mt-3 pt-3 border-t border-gray-200 flex gap-2">
                            <Link
                              href={`/employees/${employee.id}`}
                              className="flex-1 text-center py-1.5 text-ekf-orange hover:bg-primary-50 rounded text-sm font-medium transition-colors"
                            >
                              Досье
                            </Link>
                            <Link
                              href={`/analytics?employee=${employee.id}`}
                              className="flex-1 text-center py-1.5 text-ekf-orange hover:bg-primary-50 rounded text-sm font-medium transition-colors"
                            >
                              Аналитика
                            </Link>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}

          {/* List View */}
          {viewMode === 'list' && (
            <div className="bg-white rounded-lg shadow-sm border overflow-hidden">
              <table className="w-full">
                <thead className="bg-gray-50 border-b">
                  <tr>
                    <th className="text-left px-4 py-3 text-sm font-medium text-ekf-gray">Сотрудник</th>
                    <th className="text-left px-4 py-3 text-sm font-medium text-ekf-gray">Должность</th>
                    <th className="text-left px-4 py-3 text-sm font-medium text-ekf-gray">Отдел</th>
                    <th className="text-left px-4 py-3 text-sm font-medium text-ekf-gray">Контакты</th>
                    <th className="w-20"></th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {employees.map((employee) => (
                    <tr key={employee.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 bg-gray-200 rounded-full flex items-center justify-center overflow-hidden">
                            {employee.photo_base64 ? (
                              <img
                                src={`data:image/jpeg;base64,${employee.photo_base64}`}
                                alt=""
                                className="w-full h-full object-cover"
                              />
                            ) : (
                              <User size={16} className="text-ekf-gray" />
                            )}
                          </div>
                          <Link
                            href={`/employees/${employee.id}`}
                            className="font-medium text-ekf-orange hover:underline"
                          >
                            {employee.name}
                          </Link>
                        </div>
                      </td>
                      <td className="px-4 py-3 text-sm text-ekf-dark">{employee.position}</td>
                      <td className="px-4 py-3 text-sm text-ekf-gray">{employee.department || '-'}</td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-3 text-sm text-ekf-gray">
                          {employee.email && (
                            <span className="flex items-center gap-1">
                              <Mail size={12} />
                              <span className="truncate max-w-32">{employee.email}</span>
                            </span>
                          )}
                          {(employee.phone || employee.mobile) && (
                            <span className="flex items-center gap-1">
                              <Phone size={12} />
                              {employee.mobile || employee.phone}
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <button
                          onClick={() => openModal(employee)}
                          className="p-1 text-ekf-gray-light hover:text-ekf-orange"
                        >
                          <Edit size={14} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl w-full max-w-md mx-4">
            <div className="p-6 border-b">
              <h2 className="text-lg font-semibold text-ekf-dark">
                {editingEmployee ? 'Редактировать сотрудника' : 'Новый сотрудник'}
              </h2>
            </div>
            <form onSubmit={handleSubmit} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-ekf-dark mb-1">ФИО</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:border-ekf-orange focus:ring-1 focus:ring-ekf-orange outline-none"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-ekf-dark mb-1">Должность</label>
                <input
                  type="text"
                  value={formData.position}
                  onChange={(e) => setFormData({ ...formData, position: e.target.value })}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:border-ekf-orange focus:ring-1 focus:ring-ekf-orange outline-none"
                  required
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-ekf-dark mb-1">Частота встреч</label>
                  <select
                    value={formData.meeting_frequency}
                    onChange={(e) => setFormData({ ...formData, meeting_frequency: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:border-ekf-orange focus:ring-1 focus:ring-ekf-orange outline-none"
                  >
                    <option value="weekly">Еженедельно</option>
                    <option value="biweekly">Раз в 2 недели</option>
                    <option value="monthly">Ежемесячно</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-ekf-dark mb-1">День встречи</label>
                  <select
                    value={formData.meeting_day}
                    onChange={(e) => setFormData({ ...formData, meeting_day: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:border-ekf-orange focus:ring-1 focus:ring-ekf-orange outline-none"
                  >
                    <option value="">Не задан</option>
                    <option value="monday">Понедельник</option>
                    <option value="tuesday">Вторник</option>
                    <option value="wednesday">Среда</option>
                    <option value="thursday">Четверг</option>
                    <option value="friday">Пятница</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-ekf-dark mb-1">Приоритеты развития</label>
                <textarea
                  value={formData.development_priorities}
                  onChange={(e) => setFormData({ ...formData, development_priorities: e.target.value })}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 focus:border-ekf-orange focus:ring-1 focus:ring-ekf-orange outline-none"
                  rows={3}
                />
              </div>
              <div className="flex gap-3 pt-4">
                <button
                  type="button"
                  onClick={closeModal}
                  className="flex-1 py-2 border border-gray-200 text-ekf-dark rounded-lg hover:bg-gray-50 transition-colors"
                >
                  Отмена
                </button>
                <button
                  type="submit"
                  className="flex-1 py-2 bg-ekf-orange text-white rounded-lg hover:bg-ekf-orange-dark transition-colors"
                >
                  {editingEmployee ? 'Сохранить' : 'Добавить'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/routes/employees/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { employees as employeesApi } from '$lib/api/client';
	import type { Employee } from '$lib/api/client';
	import { notifications } from '$lib/stores/app';
	import { user, subordinates } from '$lib/stores/auth';

	let allEmployees: Employee[] = $state([]);
	let loading = $state(true);
	let searchQuery = $state('');
	let viewMode = $state<'my' | 'all'>('my');
	let displayMode = $state<'grid' | 'list' | 'hierarchy' | 'department'>('grid');
	let collapsedDepts: Set<string> = $state(new Set());
	let collapsedNodes: Set<string> = $state(new Set());

	// Helper: get all descendants recursively
	function getAllDescendants(managerId: string, allEmps: Employee[]): Employee[] {
		const direct = allEmps.filter(e => e.manager_id === managerId);
		const all: Employee[] = [...direct];
		for (const emp of direct) {
			all.push(...getAllDescendants(emp.id, allEmps));
		}
		return all;
	}

	// Filter employees based on view mode and department presence
	let visibleEmployees = $derived(() => {
		let employees: Employee[];

		if (viewMode === 'my') {
			// Show full tree: user's subordinates + their subordinates recursively
			if ($user?.id) {
				employees = getAllDescendants($user.id, allEmployees);
			} else {
				employees = $subordinates;
			}
		} else {
			// Show all employees with department
			employees = allEmployees.filter(e => e.department && e.department.trim() !== '');
		}

		// Apply search filter
		if (searchQuery.trim()) {
			const query = searchQuery.toLowerCase();
			employees = employees.filter(e =>
				e.name.toLowerCase().includes(query) ||
				e.position?.toLowerCase().includes(query) ||
				e.department?.toLowerCase().includes(query)
			);
		}

		return employees;
	});

	// Group employees by department for hierarchy view
	let employeesByDepartment = $derived(() => {
		const grouped: Record<string, Employee[]> = {};
		const employees = visibleEmployees();

		for (const emp of employees) {
			const dept = emp.department || 'Без отдела';
			if (!grouped[dept]) {
				grouped[dept] = [];
			}
			grouped[dept].push(emp);
		}

		// Sort departments alphabetically
		const sorted: Record<string, Employee[]> = {};
		Object.keys(grouped).sort().forEach(key => {
			sorted[key] = grouped[key].sort((a, b) => a.name.localeCompare(b.name));
		});

		return sorted;
	});

	// Build hierarchy tree (manager -> subordinates)
	let hierarchyTree = $derived(() => {
		const employees = visibleEmployees();
		const byId = new Map(employees.map(e => [e.id, e]));
		const children: Map<string, Employee[]> = new Map();

		// Build children map for all employees
		for (const emp of allEmployees) {
			if (emp.manager_id) {
				if (!children.has(emp.manager_id)) {
					children.set(emp.manager_id, []);
				}
				children.get(emp.manager_id)!.push(emp);
			}
		}

		// Sort children by name
		children.forEach(list => list.sort((a, b) => a.name.localeCompare(b.name)));

		// Find roots: employees whose manager is not in the visible set or is the current user
		const roots: Employee[] = [];
		for (const emp of employees) {
			const isDirectReport = emp.manager_id === $user?.id;
			const managerNotVisible = !emp.manager_id || !byId.has(emp.manager_id);
			if (isDirectReport || managerNotVisible) {
				roots.push(emp);
			}
		}

		return { roots: roots.sort((a, b) => a.name.localeCompare(b.name)), children };
	});

	function toggleDept(dept: string) {
		if (collapsedDepts.has(dept)) {
			collapsedDepts.delete(dept);
		} else {
			collapsedDepts.add(dept);
		}
		collapsedDepts = new Set(collapsedDepts);
	}

	function toggleNode(id: string) {
		if (collapsedNodes.has(id)) {
			collapsedNodes.delete(id);
		} else {
			collapsedNodes.add(id);
		}
		collapsedNodes = new Set(collapsedNodes);
	}

	onMount(async () => {
		try {
			allEmployees = await employeesApi.list();
			// Start with all departments collapsed
			const depts = new Set(allEmployees.map(e => e.department || 'Без отдела'));
			collapsedDepts = depts;
		} catch (e) {
			notifications.add({
				type: 'error',
				message: 'Ошибка загрузки сотрудников'
			});
		} finally {
			loading = false;
		}
	});
</script>

<svelte:head>
	<title>Сотрудники - EKF Team Hub</title>
</svelte:head>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex items-center justify-between flex-wrap gap-4">
		<h1 class="text-2xl font-bold text-gray-900">Сотрудники</h1>
		<div class="flex items-center gap-4">
			<!-- My/All Toggle -->
			<div class="flex rounded-lg border border-gray-200 overflow-hidden">
				<button
					onclick={() => viewMode = 'my'}
					class="px-4 py-2 text-sm font-medium transition-colors
						{viewMode === 'my' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
				>
					Мои ({$subordinates.length})
				</button>
				<button
					onclick={() => viewMode = 'all'}
					class="px-4 py-2 text-sm font-medium transition-colors
						{viewMode === 'all' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
				>
					Все ({allEmployees.filter(e => e.department).length})
				</button>
			</div>

			<!-- View Mode Toggle -->
			<div class="flex rounded-lg border border-gray-200 overflow-hidden">
				<button
					onclick={() => displayMode = 'grid'}
					class="p-2 transition-colors {displayMode === 'grid' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
					title="Сетка"
				>
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
					</svg>
				</button>
				<button
					onclick={() => displayMode = 'list'}
					class="p-2 transition-colors {displayMode === 'list' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
					title="Список"
				>
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 10h16M4 14h16M4 18h16" />
					</svg>
				</button>
				<button
					onclick={() => displayMode = 'hierarchy'}
					class="p-2 transition-colors {displayMode === 'hierarchy' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
					title="Оргструктура"
				>
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
					</svg>
				</button>
				<button
					onclick={() => displayMode = 'department'}
					class="p-2 transition-colors {displayMode === 'department' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
					title="По департаментам"
				>
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
					</svg>
				</button>
			</div>

			<a
				href="/employees/new"
				class="px-4 py-2 bg-ekf-red text-white rounded-lg hover:bg-red-700 transition-colors"
			>
				+ Добавить
			</a>
		</div>
	</div>

	<!-- Search -->
	<div class="relative">
		<input
			type="text"
			bind:value={searchQuery}
			placeholder="Поиск сотрудников..."
			class="w-full px-4 py-3 pl-10 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-ekf-red/20 focus:border-ekf-red"
		/>
		<svg class="w-5 h-5 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
		</svg>
	</div>

	<!-- Content -->
	{#if loading}
		<div class="flex items-center justify-center h-64">
			<div class="animate-spin rounded-full h-8 w-8 border-b-2 border-ekf-red"></div>
		</div>
	{:else if viewMode === 'my' && $subordinates.length === 0}
		<div class="text-center py-12 bg-white rounded-xl shadow-sm">
			<svg class="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
			</svg>
			<p class="text-gray-500 text-lg">У вас нет подчинённых</p>
			<button
				onclick={() => viewMode = 'all'}
				class="mt-4 text-ekf-red hover:underline"
			>
				Посмотреть всех сотрудников
			</button>
		</div>
	{:else if displayMode === 'grid'}
		<!-- Grid View -->
		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
			{#each visibleEmployees() as employee (employee.id)}
				<a
					href="/employees/{employee.id}"
					class="bg-white rounded-xl shadow-sm p-4 hover:shadow-md transition-shadow"
				>
					<div class="flex items-center gap-4">
						<div class="w-12 h-12 rounded-full bg-gray-200 flex items-center justify-center text-xl font-medium text-gray-600 flex-shrink-0">
							{#if employee.photo_base64}
								<img
									src="data:image/jpeg;base64,{employee.photo_base64}"
									alt={employee.name}
									class="w-full h-full rounded-full object-cover"
								/>
							{:else}
								{employee.name.charAt(0)}
							{/if}
						</div>
						<div class="flex-1 min-w-0">
							<p class="font-semibold text-gray-900 truncate">{employee.name}</p>
							<p class="text-sm text-gray-500 truncate">{employee.position}</p>
							{#if employee.department}
								<p class="text-xs text-gray-400 truncate">{employee.department}</p>
							{/if}
						</div>
					</div>
				</a>
			{/each}
		</div>
	{:else if displayMode === 'list'}
		<!-- List View -->
		<div class="bg-white rounded-xl shadow-sm overflow-hidden">
			<table class="w-full">
				<thead class="bg-gray-50 border-b">
					<tr>
						<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Сотрудник</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Должность</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Отдел</th>
						<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
					</tr>
				</thead>
				<tbody class="divide-y divide-gray-100">
					{#each visibleEmployees() as employee (employee.id)}
						<tr class="hover:bg-gray-50 cursor-pointer" onclick={() => window.location.href = `/employees/${employee.id}`}>
							<td class="px-6 py-4">
								<div class="flex items-center gap-3">
									<div class="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center text-sm font-medium text-gray-600 flex-shrink-0">
										{#if employee.photo_base64}
											<img
												src="data:image/jpeg;base64,{employee.photo_base64}"
												alt=""
												class="w-full h-full rounded-full object-cover"
											/>
										{:else}
											{employee.name.charAt(0)}
										{/if}
									</div>
									<span class="font-medium text-gray-900">{employee.name}</span>
								</div>
							</td>
							<td class="px-6 py-4 text-sm text-gray-600">{employee.position || '-'}</td>
							<td class="px-6 py-4 text-sm text-gray-600">{employee.department || '-'}</td>
							<td class="px-6 py-4 text-sm text-gray-600">
								{#if employee.email}
									<a href="mailto:{employee.email}" class="text-ekf-red hover:underline" onclick={(e) => e.stopPropagation()}>
										{employee.email}
									</a>
								{:else}
									-
								{/if}
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{:else if displayMode === 'hierarchy'}
		<!-- Hierarchy View by Manager -->
		<div class="bg-white rounded-xl shadow-sm p-6">
			<div class="space-y-1">
				{#each hierarchyTree().roots as employee (employee.id)}
					{@render employeeNode(employee, 0)}
				{/each}
			</div>
		</div>
	{:else if displayMode === 'department'}
		<!-- Department View with Collapsible Groups -->
		<div class="space-y-3">
			{#each Object.entries(employeesByDepartment()) as [department, employees]}
				<div class="bg-white rounded-xl shadow-sm overflow-hidden">
					<button
						onclick={() => toggleDept(department)}
						class="w-full bg-gray-50 px-6 py-3 border-b flex items-center justify-between hover:bg-gray-100 transition-colors"
					>
						<h3 class="font-semibold text-gray-900 flex items-center gap-2">
							<svg class="w-5 h-5 text-ekf-red" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
							</svg>
							{department}
							<span class="text-sm font-normal text-gray-500">({employees.length})</span>
						</h3>
						<svg
							class="w-5 h-5 text-gray-400 transition-transform {collapsedDepts.has(department) ? '' : 'rotate-180'}"
							fill="none" stroke="currentColor" viewBox="0 0 24 24"
						>
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
						</svg>
					</button>
					{#if !collapsedDepts.has(department)}
						<div class="divide-y divide-gray-100">
							{#each employees as employee (employee.id)}
								<a
									href="/employees/{employee.id}"
									class="flex items-center gap-4 px-6 py-4 hover:bg-gray-50 transition-colors"
								>
									<div class="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center text-sm font-medium text-gray-600 flex-shrink-0">
										{#if employee.photo_base64}
											<img src="data:image/jpeg;base64,{employee.photo_base64}" alt="" class="w-full h-full rounded-full object-cover" />
										{:else}
											{employee.name.charAt(0)}
										{/if}
									</div>
									<div class="flex-1 min-w-0">
										<p class="font-medium text-gray-900">{employee.name}</p>
										<p class="text-sm text-gray-500">{employee.position}</p>
									</div>
									{#if employee.email}
										<span class="text-sm text-gray-400 hidden md:block">{employee.email}</span>
									{/if}
								</a>
							{/each}
						</div>
					{/if}
				</div>
			{/each}
		</div>
	{/if}

	{#if !loading && visibleEmployees().length === 0 && (viewMode === 'all' || $subordinates.length > 0)}
		<div class="text-center py-12">
			<div class="text-gray-400 text-lg">Сотрудники не найдены</div>
		</div>
	{/if}
</div>

{#snippet employeeNode(employee: Employee, level: number)}
	{@const hasChildren = hierarchyTree().children.get(employee.id)?.length ?? 0}
	{@const isCollapsed = collapsedNodes.has(employee.id)}
	<div class="relative" style="margin-left: {level * 28}px">
		{#if level > 0}
			<div class="absolute -left-5 top-6 w-4 border-t-2 border-gray-200"></div>
			<div class="absolute -left-5 top-0 h-6 border-l-2 border-gray-200"></div>
		{/if}
		<div class="flex items-center gap-2 p-2 rounded-lg hover:bg-gray-50 transition-colors group">
			{#if hasChildren > 0}
				<button
					onclick={(e) => { e.preventDefault(); e.stopPropagation(); toggleNode(employee.id); }}
					class="w-6 h-6 flex items-center justify-center rounded hover:bg-gray-200 transition-colors flex-shrink-0"
				>
					<svg class="w-4 h-4 text-gray-500 transition-transform {isCollapsed ? '' : 'rotate-90'}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
					</svg>
				</button>
			{:else}
				<div class="w-6 h-6 flex-shrink-0"></div>
			{/if}
			<a href="/employees/{employee.id}" class="flex items-center gap-3 flex-1">
				<div class="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center text-sm font-medium text-gray-600 flex-shrink-0">
					{#if employee.photo_base64}
						<img src="data:image/jpeg;base64,{employee.photo_base64}" alt="" class="w-full h-full rounded-full object-cover" />
					{:else}
						{employee.name.charAt(0)}
					{/if}
				</div>
				<div class="flex-1 min-w-0">
					<p class="font-medium text-gray-900 group-hover:text-ekf-red transition-colors">{employee.name}</p>
					<p class="text-sm text-gray-500">{employee.position}</p>
				</div>
				{#if hasChildren > 0}
					<span class="text-xs text-gray-400 bg-gray-100 px-2 py-1 rounded">{hasChildren}</span>
				{/if}
			</a>
		</div>
		{#if hasChildren > 0 && !isCollapsed}
			<div class="relative">
				{#if level > 0}
					<div class="absolute -left-5 top-0 h-full border-l-2 border-gray-200"></div>
				{/if}
				{#each hierarchyTree().children.get(employee.id) || [] as child (child.id)}
					{@render employeeNode(child, level + 1)}
				{/each}
			</div>
		{/if}
	</div>
{/snippet}
