// frontend/src/lib/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { sidebarOpen } from '$lib/stores/app';
	import type { User } from '$lib/stores/auth';

	interface Props {
		user?: User | null;
		subordinates?: User[];
		onLogout?: () => void;
	}

	let { user = null, subordinates = [], onLogout }: Props = $props();

	const menuItems = [
		{ href: '/', label: 'Дашборд', icon: 'dashboard' },
		{ href: '/employees', label: 'Сотрудники', icon: 'users' },
		{ href: '/projects', label: 'Проекты', icon: 'folder' },
		{ href: '/meetings', label: 'Встречи', icon: 'calendar' },
		{ href: '/tasks', label: 'Задачи', icon: 'tasks' },
		{ href: '/calendar', label: 'Календарь', icon: 'schedule' },
		{ href: '/analytics', label: 'Аналитика', icon: 'chart' },
		{ href: '/upload', label: 'Загрузить запись', icon: 'upload' },
		{ href: '/script', label: 'Скрипт встречи', icon: 'script' },
		{ href: '/settings', label: 'Настройки', icon: 'settings' },
	];
</script>

<aside class="bg-ekf-dark text-white w-64 min-h-screen flex flex-col {$sidebarOpen ? '' : 'hidden lg:flex'}">
	<!-- Logo -->
	<div class="p-4 border-b border-gray-700">
		<div class="flex items-center gap-3">
			<div class="bg-ekf-red text-white font-bold text-xl px-3 py-1 rounded">
				EKF
			</div>
			<span class="text-lg font-semibold">Team Hub</span>
		</div>
	</div>

	<!-- Navigation -->
	<nav class="flex-1 p-4 overflow-y-auto">
		<ul class="space-y-1">
			{#each menuItems as item}
				<li>
					<a
						href={item.href}
						class="flex items-center gap-3 px-4 py-3 rounded-lg transition-colors
							{$page.url.pathname === item.href || ($page.url.pathname.startsWith(item.href) && item.href !== '/')
								? 'bg-ekf-red text-white'
								: 'text-gray-300 hover:bg-gray-700 hover:text-white'}"
					>
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							{#if item.icon === 'dashboard'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
							{:else if item.icon === 'users'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
							{:else if item.icon === 'folder'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
							{:else if item.icon === 'calendar'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
							{:else if item.icon === 'tasks'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
							{:else if item.icon === 'schedule'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
							{:else if item.icon === 'chart'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
							{:else if item.icon === 'upload'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
							{:else if item.icon === 'script'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
							{:else if item.icon === 'settings'}
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
							{/if}
						</svg>
						<span>{item.label}</span>
					</a>
				</li>
			{/each}
		</ul>
	</nav>

	<!-- User Info -->
	{#if user}
		<div class="p-4 border-t border-gray-700">
			<div class="flex items-center gap-3 mb-3">
				{#if user.photo_base64}
					<img src="data:image/jpeg;base64,{user.photo_base64}" alt="" class="w-10 h-10 rounded-full object-cover" />
				{:else}
					<div class="w-10 h-10 rounded-full bg-gray-600 flex items-center justify-center text-lg font-medium">
						{user.name.charAt(0)}
					</div>
				{/if}
				<div class="flex-1 min-w-0">
					<div class="text-sm font-medium truncate">{user.name}</div>
					<div class="text-xs text-gray-400 truncate">{user.position}</div>
				</div>
			</div>
			{#if subordinates.length > 0}
				<div class="text-xs text-gray-400 mb-2">
					{subordinates.length} подчинённых
				</div>
			{/if}
			{#if onLogout}
				<button
					onclick={onLogout}
					class="w-full px-3 py-2 text-sm text-gray-300 hover:text-white hover:bg-gray-700 rounded-lg transition-colors flex items-center gap-2"
				>
					<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
					</svg>
					Выйти
				</button>
			{/if}
		</div>
	{/if}
</aside>

// frontend/app/sidebar.tsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import {
  Users,
  Calendar,
  CalendarDays,
  FileText,
  Upload,
  BarChart3,
  Home,
  CheckSquare,
  LogOut,
  User,
  Settings
} from 'lucide-react'
import { useAuth } from '@/lib/auth'

export function SidebarWrapper() {
  const pathname = usePathname()

  // Don't show sidebar on login page
  if (pathname === '/login') {
    return null
  }

  return <Sidebar />
}

function Sidebar() {
  const { user, logout, subordinates } = useAuth()
  const pathname = usePathname()

  const navItems = [
    { href: '/', icon: Home, label: 'Дашборд' },
    { href: '/employees', icon: Users, label: 'Команда' },
    { href: '/calendar', icon: CalendarDays, label: 'Календарь' },
    { href: '/meetings', icon: Calendar, label: 'Встречи' },
    { href: '/tasks', icon: CheckSquare, label: 'Задачи' },
    { href: '/script', icon: FileText, label: 'Скрипт встречи' },
    { href: '/upload', icon: Upload, label: 'Загрузить запись' },
    { href: '/analytics', icon: BarChart3, label: 'Аналитика' },
    { href: '/settings', icon: Settings, label: 'Настройки' },
  ]

  const isActive = (href: string) => {
    if (href === '/') return pathname === '/'
    return pathname.startsWith(href)
  }

  return (
    <aside className="w-64 min-w-64 flex-shrink-0 bg-white border-r border-gray-200 min-h-screen flex flex-col">
      {/* Header with EKF brand */}
      <div className="p-4 border-b bg-ekf-dark">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-ekf-orange rounded flex items-center justify-center">
            <span className="text-white font-bold text-sm">EKF</span>
          </div>
          <div>
            <h1 className="text-lg font-bold text-white">Team Hub</h1>
            <p className="text-xs text-gray-400">Управление командой</p>
          </div>
        </div>
      </div>

      {/* User info */}
      {user && (
        <div className="p-4 border-b bg-gray-50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-ekf-orange/10 rounded-full flex items-center justify-center border-2 border-ekf-orange">
              <User size={20} className="text-ekf-orange" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="font-medium text-sm text-ekf-dark truncate">{user.name}</p>
              <p className="text-xs text-ekf-gray truncate">{user.position}</p>
            </div>
          </div>
          {subordinates.length > 0 && (
            <div className="mt-2 text-xs text-ekf-gray flex items-center gap-1">
              <Users size={12} />
              <span>{subordinates.length} подчинённых</span>
            </div>
          )}
        </div>
      )}

      {/* Navigation */}
      <nav className="flex-1 p-4 space-y-1">
        {navItems.map((item) => (
          <Link
            key={item.href}
            href={item.href}
            className={`flex items-center gap-3 px-3 py-2 rounded-lg transition-colors ${
              isActive(item.href)
                ? 'bg-ekf-orange/10 text-ekf-orange font-medium'
                : 'text-ekf-dark hover:bg-gray-100'
            }`}
          >
            <item.icon size={20} />
            <span>{item.label}</span>
          </Link>
        ))}
      </nav>

      {/* Logout */}
      {user && (
        <div className="p-4 border-t">
          <button
            onClick={logout}
            className="flex items-center gap-3 px-3 py-2 w-full text-ekf-gray hover:bg-gray-100 hover:text-ekf-dark rounded-lg transition-colors"
          >
            <LogOut size={20} />
            <span>Выйти</span>
          </button>
        </div>
      )}
    </aside>
  )
}
