// frontend/app/calendar/page.tsx
'use client'

import { useState, useEffect, useMemo } from 'react'
import {
  ChevronLeft,
  ChevronRight,
  Plus,
  RefreshCw,
  Clock,
  Users,
  MapPin,
  X,
  Check,
  Loader2
} from 'lucide-react'

import { API_URL } from '@/lib/config'

interface CalendarEvent {
  id: string
  subject: string
  body: string | null
  start: string
  end: string
  location: string | null
  organizer: string | null
  attendees: {
    email: string
    name: string | null
    response: string | null
    optional?: boolean
  }[]
  is_recurring: boolean
  is_cancelled: boolean
}

interface Employee {
  id: string
  name: string
  email: string
  position: string
}

interface Meeting {
  id: string
  title: string
  date: string
  exchange_id: string | null
  start_time: string | null
  end_time: string | null
  location: string | null
  participants: Employee[]
}

export default function CalendarPage() {
  const [events, setEvents] = useState<CalendarEvent[]>([])
  const [employees, setEmployees] = useState<Employee[]>([])
  const [currentDate, setCurrentDate] = useState(new Date())
  const [view, setView] = useState<'week' | 'day'>('week')
  const [loading, setLoading] = useState(true)
  const [syncing, setSyncing] = useState(false)
  const [showNewMeeting, setShowNewMeeting] = useState(false)
  const [selectedSlot, setSelectedSlot] = useState<{ date: Date; hour: number } | null>(null)
  const [connectorStatus, setConnectorStatus] = useState<boolean>(false)

  // For now, use a mock current user - will be replaced with auth
  const currentUserId = typeof window !== 'undefined'
    ? localStorage.getItem('currentUserId')
    : null

  useEffect(() => {
    checkConnectorStatus()
    fetchEmployees()
  }, [])

  useEffect(() => {
    if (currentUserId) {
      fetchCalendar()
    }
  }, [currentUserId, currentDate])

  const checkConnectorStatus = async () => {
    try {
      const res = await fetch(`${API_URL}/connector/status`)
      if (res.ok) {
        const data = await res.json()
        setConnectorStatus(data.connected)
      }
    } catch (error) {
      console.error('Failed to check connector status:', error)
    }
  }

  const fetchEmployees = async () => {
    try {
      const res = await fetch(`${API_URL}/employees`)
      if (res.ok) {
        const data = await res.json()
        setEmployees(data)
      }
    } catch (error) {
      console.error('Failed to fetch employees:', error)
    }
  }

  const fetchCalendar = async () => {
    if (!currentUserId) return

    setLoading(true)
    try {
      const res = await fetch(`${API_URL}/calendar/${currentUserId}?days_back=7&days_forward=30`)
      if (res.ok) {
        const data = await res.json()
        setEvents(Array.isArray(data) ? data : [])
      }
    } catch (error) {
      console.error('Failed to fetch calendar:', error)
    } finally {
      setLoading(false)
    }
  }

  const syncCalendar = async () => {
    if (!currentUserId) return

    setSyncing(true)
    try {
      const formData = new FormData()
      formData.append('employee_id', currentUserId)

      const res = await fetch(`${API_URL}/calendar/sync`, {
        method: 'POST',
        body: formData
      })

      if (res.ok) {
        const data = await res.json()
        alert(`Синхронизировано ${data.synced} встреч из ${data.total_events}`)
        fetchCalendar()
      }
    } catch (error) {
      console.error('Failed to sync calendar:', error)
    } finally {
      setSyncing(false)
    }
  }

  // Get week days
  const weekDays = useMemo(() => {
    const start = new Date(currentDate)
    start.setDate(start.getDate() - start.getDay() + 1) // Start from Monday

    return Array.from({ length: 7 }, (_, i) => {
      const day = new Date(start)
      day.setDate(start.getDate() + i)
      return day
    })
  }, [currentDate])

  // Hours for the time grid
  const hours = Array.from({ length: 24 }, (_, i) => i)
  const workingHours = hours.filter(h => h >= 8 && h <= 20)

  // Navigate
  const goToday = () => setCurrentDate(new Date())
  const goPrev = () => {
    const newDate = new Date(currentDate)
    newDate.setDate(newDate.getDate() - (view === 'week' ? 7 : 1))
    setCurrentDate(newDate)
  }
  const goNext = () => {
    const newDate = new Date(currentDate)
    newDate.setDate(newDate.getDate() + (view === 'week' ? 7 : 1))
    setCurrentDate(newDate)
  }

  // Get events for a specific day and hour
  const getEventsForSlot = (date: Date, hour: number) => {
    return events.filter(event => {
      if (!event.start) return false
      const eventStart = new Date(event.start)
      const eventDate = eventStart.toDateString()
      const eventHour = eventStart.getHours()
      return eventDate === date.toDateString() && eventHour === hour
    })
  }

  // Get event duration in hours
  const getEventDuration = (event: CalendarEvent) => {
    if (!event.start || !event.end) return 1
    const start = new Date(event.start)
    const end = new Date(event.end)
    return Math.max(1, (end.getTime() - start.getTime()) / (1000 * 60 * 60))
  }

  // Format date for header
  const formatWeekRange = () => {
    const start = weekDays[0]
    const end = weekDays[6]
    const options: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'long' }

    if (start.getMonth() === end.getMonth()) {
      return `${start.getDate()} - ${end.toLocaleDateString('ru-RU', options)} ${end.getFullYear()}`
    }
    return `${start.toLocaleDateString('ru-RU', options)} - ${end.toLocaleDateString('ru-RU', options)} ${end.getFullYear()}`
  }

  const isToday = (date: Date) => {
    const today = new Date()
    return date.toDateString() === today.toDateString()
  }

  // Handle slot click for creating new meeting
  const handleSlotClick = (date: Date, hour: number) => {
    setSelectedSlot({ date, hour })
    setShowNewMeeting(true)
  }

  if (!currentUserId) {
    return (
      <div className="flex flex-col items-center justify-center h-96">
        <Users size={48} className="text-gray-400 mb-4" />
        <p className="text-gray-600 mb-4">Выберите текущего пользователя</p>
        <select
          className="px-4 py-2 border rounded-lg"
          onChange={(e) => {
            localStorage.setItem('currentUserId', e.target.value)
            window.location.reload()
          }}
        >
          <option value="">Выберите сотрудника...</option>
          {employees.map(emp => (
            <option key={emp.id} value={emp.id}>
              {emp.name} ({emp.email})
            </option>
          ))}
        </select>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-4">
          <h1 className="text-2xl font-bold text-gray-900">Календарь</h1>
          <div className="flex items-center gap-1">
            <button
              onClick={goPrev}
              className="p-2 hover:bg-gray-100 rounded-lg"
            >
              <ChevronLeft size={20} />
            </button>
            <button
              onClick={goToday}
              className="px-3 py-1 text-sm hover:bg-gray-100 rounded-lg"
            >
              Сегодня
            </button>
            <button
              onClick={goNext}
              className="p-2 hover:bg-gray-100 rounded-lg"
            >
              <ChevronRight size={20} />
            </button>
          </div>
          <span className="text-lg font-medium text-gray-700">
            {formatWeekRange()}
          </span>
        </div>

        <div className="flex items-center gap-2">
          {/* View toggle */}
          <div className="flex border rounded-lg overflow-hidden">
            <button
              onClick={() => setView('day')}
              className={`px-3 py-1 text-sm ${view === 'day' ? 'bg-blue-600 text-white' : 'hover:bg-gray-100'}`}
            >
              День
            </button>
            <button
              onClick={() => setView('week')}
              className={`px-3 py-1 text-sm ${view === 'week' ? 'bg-blue-600 text-white' : 'hover:bg-gray-100'}`}
            >
              Неделя
            </button>
          </div>

          {/* Connector status */}
          <div className={`flex items-center gap-1 px-2 py-1 rounded text-xs ${
            connectorStatus ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
          }`}>
            <div className={`w-2 h-2 rounded-full ${connectorStatus ? 'bg-green-500' : 'bg-red-500'}`} />
            {connectorStatus ? 'Exchange' : 'Нет связи'}
          </div>

          {/* Sync button */}
          <button
            onClick={syncCalendar}
            disabled={syncing || !connectorStatus}
            className="flex items-center gap-2 px-3 py-2 text-sm border rounded-lg hover:bg-gray-100 disabled:opacity-50"
          >
            <RefreshCw size={16} className={syncing ? 'animate-spin' : ''} />
            Синхронизировать
          </button>

          {/* New meeting button */}
          <button
            onClick={() => setShowNewMeeting(true)}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            <Plus size={16} />
            Новая встреча
          </button>
        </div>
      </div>

      {/* Calendar Grid */}
      {loading ? (
        <div className="flex items-center justify-center h-96">
          <Loader2 className="animate-spin text-blue-600" size={32} />
        </div>
      ) : (
        <div className="flex-1 bg-white rounded-lg shadow-sm border overflow-hidden">
          <div className="flex flex-col h-full">
            {/* Day headers */}
            <div className="flex border-b bg-gray-50">
              <div className="w-16 flex-shrink-0 border-r" /> {/* Time column */}
              {(view === 'week' ? weekDays : [currentDate]).map((day, i) => (
                <div
                  key={i}
                  className={`flex-1 p-2 text-center border-r last:border-r-0 ${
                    isToday(day) ? 'bg-blue-50' : ''
                  }`}
                >
                  <div className="text-xs text-gray-500">
                    {day.toLocaleDateString('ru-RU', { weekday: 'short' })}
                  </div>
                  <div className={`text-lg font-semibold ${
                    isToday(day) ? 'text-blue-600' : 'text-gray-900'
                  }`}>
                    {day.getDate()}
                  </div>
                </div>
              ))}
            </div>

            {/* Time grid */}
            <div className="flex-1 overflow-y-auto">
              {workingHours.map(hour => (
                <div key={hour} className="flex border-b min-h-[60px]">
                  {/* Time label */}
                  <div className="w-16 flex-shrink-0 border-r p-1 text-xs text-gray-500 text-right pr-2">
                    {hour.toString().padStart(2, '0')}:00
                  </div>

                  {/* Day cells */}
                  {(view === 'week' ? weekDays : [currentDate]).map((day, dayIndex) => {
                    const slotEvents = getEventsForSlot(day, hour)

                    return (
                      <div
                        key={dayIndex}
                        className={`flex-1 border-r last:border-r-0 p-1 cursor-pointer hover:bg-gray-50 ${
                          isToday(day) ? 'bg-blue-50/30' : ''
                        }`}
                        onClick={() => handleSlotClick(day, hour)}
                      >
                        {slotEvents.map((event, eventIndex) => (
                          <div
                            key={eventIndex}
                            className="bg-blue-500 text-white text-xs p-1 rounded mb-1 cursor-pointer hover:bg-blue-600"
                            style={{
                              minHeight: `${Math.min(getEventDuration(event), 3) * 50}px`
                            }}
                            onClick={(e) => {
                              e.stopPropagation()
                              // TODO: Open event details
                            }}
                          >
                            <div className="font-medium truncate">{event.subject}</div>
                            <div className="opacity-75 truncate">
                              {new Date(event.start).toLocaleTimeString('ru-RU', {
                                hour: '2-digit',
                                minute: '2-digit'
                              })}
                              {event.location && ` - ${event.location}`}
                            </div>
                            {event.attendees && event.attendees.length > 0 && (
                              <div className="opacity-75 truncate text-[10px] mt-0.5">
                                <Users size={10} className="inline mr-1" />
                                {event.attendees.length} участников
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )
                  })}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* New Meeting Modal */}
      {showNewMeeting && (
        <NewMeetingModal
          employees={employees}
          currentUserId={currentUserId}
          initialDate={selectedSlot?.date || new Date()}
          initialHour={selectedSlot?.hour || 10}
          connectorStatus={connectorStatus}
          onClose={() => {
            setShowNewMeeting(false)
            setSelectedSlot(null)
          }}
          onCreated={() => {
            setShowNewMeeting(false)
            setSelectedSlot(null)
            fetchCalendar()
          }}
        />
      )}
    </div>
  )
}

// New Meeting Modal Component
function NewMeetingModal({
  employees,
  currentUserId,
  initialDate,
  initialHour,
  connectorStatus,
  onClose,
  onCreated
}: {
  employees: Employee[]
  currentUserId: string
  initialDate: Date
  initialHour: number
  connectorStatus: boolean
  onClose: () => void
  onCreated: () => void
}) {
  const [subject, setSubject] = useState('')
  const [body, setBody] = useState('')
  const [location, setLocation] = useState('')
  const [startDate, setStartDate] = useState(initialDate.toISOString().split('T')[0])
  const [startTime, setStartTime] = useState(`${initialHour.toString().padStart(2, '0')}:00`)
  const [endTime, setEndTime] = useState(`${(initialHour + 1).toString().padStart(2, '0')}:00`)
  const [selectedAttendees, setSelectedAttendees] = useState<string[]>([])
  const [creating, setCreating] = useState(false)
  const [findingSlots, setFindingSlots] = useState(false)
  const [freeSlots, setFreeSlots] = useState<{ start: string; end: string }[]>([])

  const handleCreate = async () => {
    if (!subject.trim()) {
      alert('Введите тему встречи')
      return
    }

    setCreating(true)
    try {
      const formData = new FormData()
      formData.append('organizer_id', currentUserId)
      formData.append('subject', subject)
      formData.append('start', `${startDate}T${startTime}:00`)
      formData.append('end', `${startDate}T${endTime}:00`)
      formData.append('attendee_ids', JSON.stringify(selectedAttendees))
      formData.append('body', body)
      formData.append('location', location)

      const res = await fetch(`${API_URL}/calendar/meeting`, {
        method: 'POST',
        body: formData
      })

      if (res.ok) {
        onCreated()
      } else {
        const error = await res.json()
        alert(`Ошибка: ${error.detail || 'Не удалось создать встречу'}`)
      }
    } catch (error) {
      console.error('Failed to create meeting:', error)
      alert('Ошибка при создании встречи')
    } finally {
      setCreating(false)
    }
  }

  const findFreeSlots = async () => {
    if (selectedAttendees.length === 0) {
      alert('Выберите участников')
      return
    }

    setFindingSlots(true)
    try {
      const startDateTime = new Date(startDate)
      startDateTime.setHours(8, 0, 0, 0)

      const endDateTime = new Date(startDate)
      endDateTime.setHours(20, 0, 0, 0)

      const params = new URLSearchParams({
        attendee_ids: [...selectedAttendees, currentUserId].join(','),
        duration_minutes: '60',
        start: startDateTime.toISOString(),
        end: endDateTime.toISOString()
      })

      const res = await fetch(`${API_URL}/calendar/free-slots?${params}`)
      if (res.ok) {
        const data = await res.json()
        setFreeSlots(data)
      }
    } catch (error) {
      console.error('Failed to find free slots:', error)
    } finally {
      setFindingSlots(false)
    }
  }

  const toggleAttendee = (id: string) => {
    setSelectedAttendees(prev =>
      prev.includes(id)
        ? prev.filter(a => a !== id)
        : [...prev, id]
    )
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b">
          <h2 className="text-lg font-semibold">Новая встреча</h2>
          <button onClick={onClose} className="p-1 hover:bg-gray-100 rounded">
            <X size={20} />
          </button>
        </div>

        {/* Form */}
        <div className="p-4 space-y-4">
          {/* Subject */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Тема встречи *
            </label>
            <input
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="Например: 1-на-1 с Иваном"
            />
          </div>

          {/* Date and Time */}
          <div className="grid grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Дата
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full px-3 py-2 border rounded-lg"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Начало
              </label>
              <input
                type="time"
                value={startTime}
                onChange={(e) => setStartTime(e.target.value)}
                className="w-full px-3 py-2 border rounded-lg"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Окончание
              </label>
              <input
                type="time"
                value={endTime}
                onChange={(e) => setEndTime(e.target.value)}
                className="w-full px-3 py-2 border rounded-lg"
              />
            </div>
          </div>

          {/* Location */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              <MapPin size={14} className="inline mr-1" />
              Место
            </label>
            <input
              type="text"
              value={location}
              onChange={(e) => setLocation(e.target.value)}
              className="w-full px-3 py-2 border rounded-lg"
              placeholder="Переговорная или ссылка на Zoom"
            />
          </div>

          {/* Attendees */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-sm font-medium text-gray-700">
                <Users size={14} className="inline mr-1" />
                Участники
              </label>
              {connectorStatus && selectedAttendees.length > 0 && (
                <button
                  onClick={findFreeSlots}
                  disabled={findingSlots}
                  className="text-sm text-blue-600 hover:underline flex items-center gap-1"
                >
                  <Clock size={14} />
                  {findingSlots ? 'Поиск...' : 'Найти свободное время'}
                </button>
              )}
            </div>

            <div className="border rounded-lg max-h-40 overflow-y-auto">
              {employees
                .filter(emp => emp.id !== currentUserId)
                .map(emp => (
                  <label
                    key={emp.id}
                    className="flex items-center gap-3 p-2 hover:bg-gray-50 cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={selectedAttendees.includes(emp.id)}
                      onChange={() => toggleAttendee(emp.id)}
                      className="rounded text-blue-600"
                    />
                    <div>
                      <div className="font-medium text-sm">{emp.name}</div>
                      <div className="text-xs text-gray-500">{emp.position}</div>
                    </div>
                  </label>
                ))}
            </div>
          </div>

          {/* Free Slots */}
          {freeSlots.length > 0 && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Свободные слоты
              </label>
              <div className="flex flex-wrap gap-2">
                {freeSlots.slice(0, 5).map((slot, i) => (
                  <button
                    key={i}
                    onClick={() => {
                      const start = new Date(slot.start)
                      setStartTime(`${start.getHours().toString().padStart(2, '0')}:${start.getMinutes().toString().padStart(2, '0')}`)
                      const end = new Date(slot.start)
                      end.setHours(end.getHours() + 1)
                      setEndTime(`${end.getHours().toString().padStart(2, '0')}:${end.getMinutes().toString().padStart(2, '0')}`)
                    }}
                    className="px-3 py-1 text-sm border rounded-lg hover:bg-blue-50 hover:border-blue-300"
                  >
                    {new Date(slot.start).toLocaleTimeString('ru-RU', {
                      hour: '2-digit',
                      minute: '2-digit'
                    })}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Description */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Описание
            </label>
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={3}
              className="w-full px-3 py-2 border rounded-lg resize-none"
              placeholder="Повестка встречи..."
            />
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-4 border-t bg-gray-50">
          <div className="text-sm text-gray-500">
            {connectorStatus
              ? 'Встреча будет создана в Exchange и отправлены приглашения'
              : 'Exchange недоступен - встреча будет создана только в приложении'
            }
          </div>
          <div className="flex gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 border rounded-lg hover:bg-gray-100"
            >
              Отмена
            </button>
            <button
              onClick={handleCreate}
              disabled={creating || !subject.trim()}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 flex items-center gap-2"
            >
              {creating ? (
                <>
                  <Loader2 size={16} className="animate-spin" />
                  Создание...
                </>
              ) : (
                <>
                  <Check size={16} />
                  Создать встречу
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/routes/calendar/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { calendar as calendarApi, meetings as meetingsApi } from '$lib/api/client';
	import type { CalendarEvent } from '$lib/api/client';
	import { user, subordinates } from '$lib/stores/auth';

	let events: CalendarEvent[] = $state([]);
	let loading = $state(true);
	let syncing = $state(false);
	let showSyncDialog = $state(false);
	let showEventDialog = $state(false);

	let currentDate = $state(new Date());
	let viewMode = $state<'week' | 'month'>('month');

	// Exchange credentials (stored in localStorage)
	let exchangeUser = $state('');
	let exchangePass = $state('');

	// New event form
	let newEvent = $state({
		title: '',
		date: '',
		start_time: '',
		end_time: '',
		location: '',
		employee_id: ''
	});

	const weekDays = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'];
	const months = [
		'Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
		'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'
	];

	onMount(async () => {
		// Load saved credentials
		exchangeUser = localStorage.getItem('exchange_user') || '';
		if ($user?.id) {
			await loadCalendar();
		}
	});

	async function loadCalendar() {
		if (!$user?.id) return;
		loading = true;
		try {
			const response = await calendarApi.getSimple($user.id);
			events = Array.isArray(response) ? response : (response.events || []);
		} catch (e) {
			console.error(e);
			events = [];
		} finally {
			loading = false;
		}
	}

	function openSyncDialog() {
		showSyncDialog = true;
	}

	async function syncCalendar() {
		if (!$user?.id || !exchangeUser || !exchangePass) return;

		syncing = true;
		try {
			localStorage.setItem('exchange_user', exchangeUser);
			await calendarApi.sync({
				employee_id: $user.id,
				username: exchangeUser,
				password: exchangePass,
				days_back: 30,
				days_forward: 60
			});
			await loadCalendar();
			showSyncDialog = false;
		} catch (e: any) {
			console.error(e);
			alert('Ошибка синхронизации: ' + (e.message || 'Проверьте учётные данные'));
		} finally {
			syncing = false;
		}
	}

	function openNewEventDialog(date?: Date) {
		const d = date || new Date();
		newEvent = {
			title: '',
			date: d.toISOString().split('T')[0],
			start_time: '09:00',
			end_time: '10:00',
			location: '',
			employee_id: $user?.id || ''
		};
		showEventDialog = true;
	}

	async function createEvent() {
		if (!newEvent.title || !newEvent.date) return;

		try {
			await meetingsApi.create({
				title: newEvent.title,
				date: newEvent.date,
				start_time: `${newEvent.date}T${newEvent.start_time}:00`,
				end_time: `${newEvent.date}T${newEvent.end_time}:00`,
				location: newEvent.location || undefined,
				employee_id: newEvent.employee_id || undefined
			});
			await loadCalendar();
			showEventDialog = false;
		} catch (e) {
			console.error(e);
			alert('Ошибка создания события');
		}
	}

	function getWeekDates(): Date[] {
		const start = new Date(currentDate);
		const day = start.getDay();
		const diff = start.getDate() - day + (day === 0 ? -6 : 1);
		start.setDate(diff);

		return Array.from({ length: 7 }, (_, i) => {
			const date = new Date(start);
			date.setDate(start.getDate() + i);
			return date;
		});
	}

	function getMonthDates(): Date[][] {
		const year = currentDate.getFullYear();
		const month = currentDate.getMonth();
		const firstDay = new Date(year, month, 1);
		const lastDay = new Date(year, month + 1, 0);

		const startDay = firstDay.getDay() || 7;
		const weeks: Date[][] = [];
		let currentWeek: Date[] = [];

		// Fill in days from previous month
		for (let i = startDay - 1; i > 0; i--) {
			const d = new Date(year, month, 1 - i);
			currentWeek.push(d);
		}

		// Fill in days of current month
		for (let day = 1; day <= lastDay.getDate(); day++) {
			currentWeek.push(new Date(year, month, day));
			if (currentWeek.length === 7) {
				weeks.push(currentWeek);
				currentWeek = [];
			}
		}

		// Fill remaining days from next month
		if (currentWeek.length > 0) {
			let nextDay = 1;
			while (currentWeek.length < 7) {
				currentWeek.push(new Date(year, month + 1, nextDay++));
			}
			weeks.push(currentWeek);
		}

		return weeks;
	}

	function getEventsForDate(date: Date): CalendarEvent[] {
		const dateStr = date.toISOString().split('T')[0];
		return events.filter(e => {
			const eventDate = e.start?.split('T')[0] || e.date;
			return eventDate === dateStr;
		});
	}

	function formatTime(isoString: string): string {
		if (!isoString) return '';
		const date = new Date(isoString);
		return date.toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' });
	}

	function prevPeriod() {
		const newDate = new Date(currentDate);
		if (viewMode === 'week') {
			newDate.setDate(newDate.getDate() - 7);
		} else {
			newDate.setMonth(newDate.getMonth() - 1);
		}
		currentDate = newDate;
	}

	function nextPeriod() {
		const newDate = new Date(currentDate);
		if (viewMode === 'week') {
			newDate.setDate(newDate.getDate() + 7);
		} else {
			newDate.setMonth(newDate.getMonth() + 1);
		}
		currentDate = newDate;
	}

	function isToday(date: Date): boolean {
		const today = new Date();
		return date.toDateString() === today.toDateString();
	}

	function isCurrentMonth(date: Date): boolean {
		return date.getMonth() === currentDate.getMonth();
	}

	$effect(() => {
		if ($user?.id) {
			loadCalendar();
		}
	});
</script>

<svelte:head>
	<title>Календарь - EKF Team Hub</title>
</svelte:head>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-2xl font-bold text-gray-900">Мой календарь</h1>
			{#if $user}
				<p class="text-gray-500">{$user.name}</p>
			{/if}
		</div>
		<div class="flex items-center gap-3">
			<button
				onclick={() => openNewEventDialog()}
				class="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors flex items-center gap-2"
			>
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
				</svg>
				Новая встреча
			</button>
			<button
				onclick={openSyncDialog}
				class="px-4 py-2 bg-ekf-red text-white rounded-lg hover:bg-red-700 transition-colors flex items-center gap-2"
			>
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
				</svg>
				Синхронизировать
			</button>
		</div>
	</div>

	<!-- Navigation -->
	<div class="bg-white rounded-xl shadow-sm p-4">
		<div class="flex items-center justify-between">
			<button
				onclick={prevPeriod}
				class="p-2 hover:bg-gray-100 rounded-lg transition-colors"
			>
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
				</svg>
			</button>
			<div class="flex items-center gap-4">
				<div class="text-lg font-semibold text-gray-900">
					{months[currentDate.getMonth()]} {currentDate.getFullYear()}
				</div>
				<div class="flex rounded-lg border border-gray-200 overflow-hidden">
					<button
						onclick={() => viewMode = 'week'}
						class="px-3 py-1 text-sm {viewMode === 'week' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
					>
						Неделя
					</button>
					<button
						onclick={() => viewMode = 'month'}
						class="px-3 py-1 text-sm {viewMode === 'month' ? 'bg-ekf-red text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}"
					>
						Месяц
					</button>
				</div>
			</div>
			<button
				onclick={nextPeriod}
				class="p-2 hover:bg-gray-100 rounded-lg transition-colors"
			>
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
				</svg>
			</button>
		</div>
	</div>

	<!-- Calendar Grid -->
	{#if loading}
		<div class="flex items-center justify-center h-64">
			<div class="text-gray-500">Загрузка...</div>
		</div>
	{:else if viewMode === 'week'}
		<div class="bg-white rounded-xl shadow-sm overflow-hidden">
			<div class="grid grid-cols-7 border-b">
				{#each getWeekDates() as date, i}
					<div class="p-4 text-center border-r last:border-r-0 {isToday(date) ? 'bg-ekf-red/5' : ''}">
						<div class="text-sm text-gray-500">{weekDays[i]}</div>
						<div class="text-lg font-semibold mt-1 {isToday(date) ? 'text-ekf-red' : 'text-gray-900'}">
							{date.getDate()}
						</div>
					</div>
				{/each}
			</div>
			<div class="grid grid-cols-7 min-h-96">
				{#each getWeekDates() as date}
					<button
						onclick={() => openNewEventDialog(date)}
						class="p-2 border-r last:border-r-0 border-b text-left hover:bg-gray-50 {isToday(date) ? 'bg-ekf-red/5' : ''}"
					>
						<div class="space-y-1">
							{#each getEventsForDate(date) as event}
								<div class="p-2 rounded text-xs bg-blue-50 border-l-2 border-blue-500">
									<div class="font-medium text-gray-900 truncate">{event.subject || event.title}</div>
									<div class="text-gray-500">
										{formatTime(event.start || event.start_time)} - {formatTime(event.end || event.end_time)}
									</div>
								</div>
							{/each}
						</div>
					</button>
				{/each}
			</div>
		</div>
	{:else}
		<div class="bg-white rounded-xl shadow-sm overflow-hidden">
			<div class="grid grid-cols-7 border-b bg-gray-50">
				{#each weekDays as day}
					<div class="p-3 text-center text-sm font-medium text-gray-600 border-r last:border-r-0">
						{day}
					</div>
				{/each}
			</div>
			{#each getMonthDates() as week}
				<div class="grid grid-cols-7 border-b last:border-b-0">
					{#each week as date}
						<button
							onclick={() => openNewEventDialog(date)}
							class="p-2 min-h-24 border-r last:border-r-0 text-left hover:bg-gray-50 transition-colors
								{isToday(date) ? 'bg-ekf-red/5' : ''}
								{!isCurrentMonth(date) ? 'bg-gray-50 text-gray-400' : ''}"
						>
							<div class="text-sm font-medium mb-1 {isToday(date) ? 'text-ekf-red' : ''}">
								{date.getDate()}
							</div>
							<div class="space-y-1">
								{#each getEventsForDate(date).slice(0, 3) as event}
									<div class="text-xs p-1 rounded bg-blue-100 text-blue-800 truncate">
										{event.subject || event.title}
									</div>
								{/each}
								{#if getEventsForDate(date).length > 3}
									<div class="text-xs text-gray-500">+{getEventsForDate(date).length - 3} ещё</div>
								{/if}
							</div>
						</button>
					{/each}
				</div>
			{/each}
		</div>
	{/if}

	<!-- Free Slots -->
	<div class="bg-white rounded-xl shadow-sm p-6">
		<h3 class="font-semibold text-gray-900 mb-4">Свободные слоты для встреч</h3>
		<p class="text-gray-500 text-sm">
			Выберите сотрудника для просмотра свободных временных слотов.
		</p>
	</div>
</div>

<!-- Sync Dialog -->
{#if showSyncDialog}
	<div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
		<div class="bg-white rounded-xl p-6 w-full max-w-md">
			<h3 class="text-lg font-semibold text-gray-900 mb-4">Синхронизация с Exchange</h3>
			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Логин Exchange</label>
					<input
						type="text"
						bind:value={exchangeUser}
						placeholder="domain\username или email"
						class="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-ekf-red/20"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Пароль</label>
					<input
						type="password"
						bind:value={exchangePass}
						class="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-ekf-red/20"
					/>
				</div>
			</div>
			<div class="mt-6 flex justify-end gap-3">
				<button
					onclick={() => showSyncDialog = false}
					class="px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
				>
					Отмена
				</button>
				<button
					onclick={syncCalendar}
					disabled={!exchangeUser || !exchangePass || syncing}
					class="px-4 py-2 bg-ekf-red text-white rounded-lg hover:bg-red-700 disabled:opacity-50"
				>
					{syncing ? 'Синхронизация...' : 'Синхронизировать'}
				</button>
			</div>
		</div>
	</div>
{/if}

<!-- New Event Dialog -->
{#if showEventDialog}
	<div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
		<div class="bg-white rounded-xl p-6 w-full max-w-md">
			<h3 class="text-lg font-semibold text-gray-900 mb-4">Новая встреча</h3>
			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Название</label>
					<input
						type="text"
						bind:value={newEvent.title}
						placeholder="Тема встречи"
						class="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-ekf-red/20"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Дата</label>
					<input
						type="date"
						bind:value={newEvent.date}
						class="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-ekf-red/20"
					/>
				</div>
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-1">Начало</label>
						<input
							type="time"
							bind:value={newEvent.start_time}
							class="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-ekf-red/20"
						/>
					</div>
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-1">Конец</label>
						<input
							type="time"
							bind:value={newEvent.end_time}
							class="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-ekf-red/20"
						/>
					</div>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Место</label>
					<input
						type="text"
						bind:value={newEvent.location}
						placeholder="Переговорная, онлайн..."
						class="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-ekf-red/20"
					/>
				</div>
			</div>
			<div class="mt-6 flex justify-end gap-3">
				<button
					onclick={() => showEventDialog = false}
					class="px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
				>
					Отмена
				</button>
				<button
					onclick={createEvent}
					disabled={!newEvent.title || !newEvent.date}
					class="px-4 py-2 bg-ekf-red text-white rounded-lg hover:bg-red-700 disabled:opacity-50"
				>
					Создать
				</button>
			</div>
		</div>
	</div>
{/if}
