// frontend/app/settings/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { Settings, Server, RefreshCw, CheckCircle, XCircle, Users, Calendar, Loader2 } from 'lucide-react'

import { API_URL } from '@/lib/config'

interface ConnectorStatus {
  connected: boolean
  last_sync: string | null
  ad_status: 'connected' | 'disconnected' | 'unknown'
  exchange_status: 'connected' | 'disconnected' | 'unknown'
}

interface SyncResult {
  success: boolean
  message: string
  count?: number
}

export default function SettingsPage() {
  const [connectorStatus, setConnectorStatus] = useState<ConnectorStatus | null>(null)
  const [loading, setLoading] = useState(true)
  const [syncing, setSyncing] = useState<string | null>(null)
  const [syncResults, setSyncResults] = useState<Record<string, SyncResult>>({})

  useEffect(() => {
    checkConnectorStatus()
  }, [])

  const checkConnectorStatus = async () => {
    setLoading(true)
    try {
      const res = await fetch(`${API_URL}/connector/status`)
      if (res.ok) {
        const data = await res.json()
        setConnectorStatus(data)
      } else {
        setConnectorStatus({
          connected: false,
          last_sync: null,
          ad_status: 'disconnected',
          exchange_status: 'disconnected'
        })
      }
    } catch (error) {
      console.error('Failed to check connector status:', error)
      setConnectorStatus({
        connected: false,
        last_sync: null,
        ad_status: 'disconnected',
        exchange_status: 'disconnected'
      })
    } finally {
      setLoading(false)
    }
  }

  const syncAD = async () => {
    setSyncing('ad')
    setSyncResults(prev => ({ ...prev, ad: { success: false, message: 'Синхронизация...' } }))
    try {
      const res = await fetch(`${API_URL}/ad/sync`, { method: 'POST' })
      const data = await res.json()
      if (res.ok) {
        setSyncResults(prev => ({
          ...prev,
          ad: { success: true, message: `Синхронизировано ${data.imported || 0} сотрудников`, count: data.imported }
        }))
      } else {
        setSyncResults(prev => ({
          ...prev,
          ad: { success: false, message: data.detail || 'Ошибка синхронизации' }
        }))
      }
    } catch (error) {
      setSyncResults(prev => ({
        ...prev,
        ad: { success: false, message: 'Коннектор недоступен' }
      }))
    } finally {
      setSyncing(null)
    }
  }

  const syncCalendar = async () => {
    setSyncing('calendar')
    setSyncResults(prev => ({ ...prev, calendar: { success: false, message: 'Синхронизация...' } }))
    try {
      const res = await fetch(`${API_URL}/calendar/sync`, { method: 'POST' })
      const data = await res.json()
      if (res.ok) {
        setSyncResults(prev => ({
          ...prev,
          calendar: { success: true, message: `Синхронизировано ${data.synced || 0} из ${data.total || 0} встреч`, count: data.synced }
        }))
      } else {
        setSyncResults(prev => ({
          ...prev,
          calendar: { success: false, message: data.detail || 'Ошибка синхронизации' }
        }))
      }
    } catch (error) {
      setSyncResults(prev => ({
        ...prev,
        calendar: { success: false, message: 'Коннектор недоступен' }
      }))
    } finally {
      setSyncing(null)
    }
  }

  const StatusIcon = ({ status }: { status: 'connected' | 'disconnected' | 'unknown' }) => {
    if (status === 'connected') return <CheckCircle size={18} className="text-green-500" />
    if (status === 'disconnected') return <XCircle size={18} className="text-red-500" />
    return <div className="w-4 h-4 rounded-full bg-gray-300" />
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-ekf-orange"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Settings size={28} className="text-ekf-orange" />
        <h1 className="text-2xl font-bold text-ekf-dark">Настройки</h1>
      </div>

      {/* Connector Status */}
      <div className="bg-white rounded-lg shadow-sm border">
        <div className="p-4 border-b">
          <h2 className="text-lg font-semibold text-ekf-dark flex items-center gap-2">
            <Server size={20} />
            On-Prem Коннектор
          </h2>
        </div>
        <div className="p-6">
          <div className="flex items-center gap-4 mb-6">
            <div className={`w-3 h-3 rounded-full ${connectorStatus?.connected ? 'bg-green-500' : 'bg-red-500'}`} />
            <span className={`font-medium ${connectorStatus?.connected ? 'text-green-600' : 'text-red-600'}`}>
              {connectorStatus?.connected ? 'Подключен' : 'Не подключен'}
            </span>
            <button
              onClick={checkConnectorStatus}
              className="ml-auto text-ekf-gray hover:text-ekf-orange transition-colors"
            >
              <RefreshCw size={18} />
            </button>
          </div>

          {!connectorStatus?.connected && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
              <p className="text-yellow-800 text-sm">
                Для синхронизации с Active Directory и Exchange необходимо запустить on-prem коннектор
                внутри корпоративной сети. Подробная инструкция в README проекта.
              </p>
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* AD Status */}
            <div className="border rounded-lg p-4">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <Users size={18} className="text-ekf-orange" />
                  <span className="font-medium">Active Directory</span>
                </div>
                <StatusIcon status={connectorStatus?.ad_status || 'unknown'} />
              </div>
              <p className="text-sm text-ekf-gray mb-4">
                Синхронизация сотрудников и оргструктуры
              </p>
              <button
                onClick={syncAD}
                disabled={syncing === 'ad' || !connectorStatus?.connected}
                className="w-full flex items-center justify-center gap-2 py-2 px-4 bg-ekf-orange text-white rounded-lg hover:bg-ekf-orange-dark disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {syncing === 'ad' ? (
                  <>
                    <Loader2 size={16} className="animate-spin" />
                    Синхронизация...
                  </>
                ) : (
                  <>
                    <RefreshCw size={16} />
                    Синхронизировать AD
                  </>
                )}
              </button>
              {syncResults.ad && (
                <p className={`mt-2 text-sm ${syncResults.ad.success ? 'text-green-600' : 'text-red-600'}`}>
                  {syncResults.ad.message}
                </p>
              )}
            </div>

            {/* Exchange Status */}
            <div className="border rounded-lg p-4">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <Calendar size={18} className="text-ekf-orange" />
                  <span className="font-medium">Exchange / Outlook</span>
                </div>
                <StatusIcon status={connectorStatus?.exchange_status || 'unknown'} />
              </div>
              <p className="text-sm text-ekf-gray mb-4">
                Синхронизация календаря и встреч
              </p>
              <button
                onClick={syncCalendar}
                disabled={syncing === 'calendar' || !connectorStatus?.connected}
                className="w-full flex items-center justify-center gap-2 py-2 px-4 bg-ekf-orange text-white rounded-lg hover:bg-ekf-orange-dark disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {syncing === 'calendar' ? (
                  <>
                    <Loader2 size={16} className="animate-spin" />
                    Синхронизация...
                  </>
                ) : (
                  <>
                    <RefreshCw size={16} />
                    Синхронизировать календарь
                  </>
                )}
              </button>
              {syncResults.calendar && (
                <p className={`mt-2 text-sm ${syncResults.calendar.success ? 'text-green-600' : 'text-red-600'}`}>
                  {syncResults.calendar.message}
                </p>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Info */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-lg font-semibold text-ekf-dark mb-4">Информация</h2>
        <div className="space-y-3 text-sm">
          <div className="flex justify-between">
            <span className="text-ekf-gray">Последняя синхронизация AD</span>
            <span className="text-ekf-dark">
              {connectorStatus?.last_sync
                ? new Date(connectorStatus.last_sync).toLocaleString('ru-RU')
                : 'Не выполнялась'}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-ekf-gray">Backend API</span>
            <span className="text-ekf-dark font-mono text-xs">{API_URL}</span>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/routes/settings/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { connector as connectorApi } from '$lib/api/client';
	import type { ConnectorStatus } from '$lib/api/client';

	let status: ConnectorStatus | null = $state(null);
	let loading = $state(true);
	let syncing = $state(false);

	onMount(async () => {
		await loadStatus();
	});

	async function loadStatus() {
		try {
			status = await connectorApi.status();
		} catch (e) {
			console.error(e);
		} finally {
			loading = false;
		}
	}

	async function syncAD() {
		syncing = true;
		try {
			await connectorApi.syncAD();
			alert('Синхронизация завершена');
			await loadStatus();
		} catch (e) {
			console.error(e);
			alert('Ошибка синхронизации');
		} finally {
			syncing = false;
		}
	}
</script>

<svelte:head>
	<title>Статус служб - EKF Team Hub</title>
</svelte:head>

<div class="max-w-4xl mx-auto space-y-6">
	<h1 class="text-2xl font-bold text-gray-900">Статус служб</h1>

	{#if loading}
		<div class="flex items-center justify-center h-64">
			<div class="text-gray-500">Загрузка...</div>
		</div>
	{:else}
		<!-- Service Status -->
		<div class="bg-white rounded-xl shadow-sm p-6">
			<div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
				<div class="p-4 rounded-lg bg-gray-50">
					<div class="text-sm text-gray-500 mb-1">Коннектор</div>
					<div class="flex items-center gap-2">
						<div class="w-3 h-3 rounded-full {status?.connected ? 'bg-green-500' : 'bg-red-500'}"></div>
						<span class="font-medium">{status?.connected ? 'Подключен' : 'Отключен'}</span>
					</div>
				</div>
				<div class="p-4 rounded-lg bg-gray-50">
					<div class="text-sm text-gray-500 mb-1">AD Sync</div>
					<div class="flex items-center gap-2">
						<div class="w-3 h-3 rounded-full {status?.ad_sync_enabled ? 'bg-green-500' : 'bg-gray-400'}"></div>
						<span class="font-medium">{status?.ad_sync_enabled ? 'Включено' : 'Выключено'}</span>
					</div>
				</div>
				<div class="p-4 rounded-lg bg-gray-50">
					<div class="text-sm text-gray-500 mb-1">Последняя синхронизация</div>
					<span class="font-medium">{status?.last_sync || 'Никогда'}</span>
				</div>
			</div>

			<div class="space-y-3 mb-6">
				<div class="flex items-center justify-between p-3 rounded-lg bg-gray-50">
					<div class="flex items-center gap-3">
						<div class="w-3 h-3 rounded-full bg-green-500"></div>
						<div>
							<div class="font-medium text-gray-900">OpenAI API</div>
							<div class="text-sm text-gray-500">Транскрибация Whisper</div>
						</div>
					</div>
				</div>

				<div class="flex items-center justify-between p-3 rounded-lg bg-gray-50">
					<div class="flex items-center gap-3">
						<div class="w-3 h-3 rounded-full bg-green-500"></div>
						<div>
							<div class="font-medium text-gray-900">Anthropic API</div>
							<div class="text-sm text-gray-500">Анализ встреч (Claude)</div>
						</div>
					</div>
				</div>

				<div class="flex items-center justify-between p-3 rounded-lg bg-gray-50">
					<div class="flex items-center gap-3">
						<div class="w-3 h-3 rounded-full {status?.ews_configured ? 'bg-green-500' : 'bg-gray-400'}"></div>
						<div>
							<div class="font-medium text-gray-900">Exchange EWS</div>
							<div class="text-sm text-gray-500">Интеграция с календарём</div>
						</div>
					</div>
				</div>

				<div class="flex items-center justify-between p-3 rounded-lg bg-gray-50">
					<div class="flex items-center gap-3">
						<div class="w-3 h-3 rounded-full bg-gray-400"></div>
						<div>
							<div class="font-medium text-gray-900">Yandex SpeechKit</div>
							<div class="text-sm text-gray-500">Альтернативная транскрибация</div>
						</div>
					</div>
				</div>
			</div>

			<button
				onclick={syncAD}
				disabled={syncing || !status?.connected}
				class="px-4 py-2 bg-ekf-red text-white rounded-lg hover:bg-red-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
			>
				{#if syncing}
					Синхронизация...
				{:else}
					Синхронизировать AD
				{/if}
			</button>
		</div>
	{/if}
</div>
