// frontend/src/routes/meetings/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { meetings as meetingsApi } from '$lib/api/client';
	import type { Meeting } from '$lib/api/client';

	let meetings: Meeting[] = $state([]);
	let loading = $state(true);
	let filter = $state('all');

	onMount(async () => {
		try {
			meetings = await meetingsApi.list();
		} catch (e) {
			console.error(e);
		} finally {
			loading = false;
		}
	});

	const filteredMeetings = $derived(() => {
		if (filter === 'all') return meetings;
		return meetings.filter(m => m.category === filter);
	});

	function formatDate(dateStr: string): string {
		const date = new Date(dateStr);
		return date.toLocaleDateString('ru-RU', { day: 'numeric', month: 'long', year: 'numeric' });
	}
</script>

<svelte:head>
	<title>Встречи - EKF Team Hub</title>
</svelte:head>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-bold text-gray-900">Встречи</h1>
		<a
			href="/meetings/new"
			class="px-4 py-2 bg-ekf-red text-white rounded-lg hover:bg-red-700 transition-colors"
		>
			Новая встреча
		</a>
	</div>

	<!-- Filters -->
	<div class="flex gap-2">
		{#each [
			{ key: 'all', label: 'Все' },
			{ key: 'one_on_one', label: '1-на-1' },
			{ key: 'project', label: 'Проектные' },
			{ key: 'team', label: 'Командные' }
		] as tab}
			<button
				onclick={() => filter = tab.key}
				class="px-4 py-2 rounded-lg text-sm font-medium transition-colors
					{filter === tab.key
						? 'bg-ekf-red text-white'
						: 'bg-white text-gray-600 hover:bg-gray-100'}"
			>
				{tab.label}
			</button>
		{/each}
	</div>

	{#if loading}
		<div class="flex items-center justify-center h-64">
			<div class="text-gray-500">Загрузка...</div>
		</div>
	{:else if filteredMeetings().length === 0}
		<div class="bg-white rounded-xl shadow-sm p-12 text-center">
			<div class="text-gray-400 text-lg mb-4">Встреч пока нет</div>
			<a
				href="/meetings/new"
				class="inline-block px-4 py-2 bg-ekf-red text-white rounded-lg hover:bg-red-700 transition-colors"
			>
				Провести первую встречу
			</a>
		</div>
	{:else}
		<div class="space-y-4">
			{#each filteredMeetings() as meeting}
				<a href="/meetings/{meeting.id}" class="block bg-white rounded-xl shadow-sm p-6 hover:shadow-md transition-shadow">
					<div class="flex items-start justify-between">
						<div class="flex-1">
							<div class="flex items-center gap-3">
								<h3 class="text-lg font-semibold text-gray-900">
									{meeting.title || 'Без названия'}
								</h3>
								{#if meeting.category}
									<span class="px-2 py-1 text-xs rounded-full bg-gray-100 text-gray-600">
										{meeting.category === 'one_on_one' ? '1-на-1' :
										meeting.category === 'project' ? 'Проект' : 'Команда'}
									</span>
								{/if}
							</div>
							<p class="text-sm text-gray-500 mt-1">{formatDate(meeting.date)}</p>
							{#if meeting.summary}
								<p class="text-gray-600 mt-3 line-clamp-2">{meeting.summary}</p>
							{/if}
						</div>
						<div class="flex flex-col items-end gap-2">
							{#if meeting.mood_score}
								<span class="text-lg font-bold
									{meeting.mood_score >= 7 ? 'text-green-600' :
									meeting.mood_score >= 5 ? 'text-yellow-600' : 'text-red-600'}">
									{meeting.mood_score}/10
								</span>
							{/if}
							{#if meeting.duration_minutes}
								<span class="text-sm text-gray-500">{meeting.duration_minutes} мин</span>
							{/if}
						</div>
					</div>
				</a>
			{/each}
		</div>
	{/if}
</div>

// frontend/app/meetings/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { Calendar, User, ChevronRight } from 'lucide-react'

import { API_URL } from '@/lib/config'

interface Meeting {
  id: string
  date: string
  mood_score: number | null
  summary: string | null
  employees: {
    name: string
    position: string
  }
}

export default function MeetingsPage() {
  const [meetings, setMeetings] = useState<Meeting[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchMeetings()
  }, [])

  const fetchMeetings = async () => {
    try {
      const res = await fetch(`${API_URL}/meetings`)
      if (res.ok) {
        const data = await res.json()
        setMeetings(data)
      }
    } catch (error) {
      console.error('Failed to fetch meetings:', error)
    } finally {
      setLoading(false)
    }
  }

  const groupByMonth = (meetings: Meeting[]) => {
    const groups: Record<string, Meeting[]> = {}
    
    meetings.forEach((meeting) => {
      const date = new Date(meeting.date)
      const key = date.toLocaleDateString('ru-RU', { month: 'long', year: 'numeric' })
      if (!groups[key]) {
        groups[key] = []
      }
      groups[key].push(meeting)
    })
    
    return groups
  }

  const groupedMeetings = groupByMonth(meetings)

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-900">Встречи</h1>
        <Link
          href="/upload"
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          Загрузить запись
        </Link>
      </div>

      {meetings.length === 0 ? (
        <div className="bg-white rounded-lg shadow-sm border p-12 text-center">
          <Calendar size={48} className="mx-auto text-gray-400 mb-4" />
          <p className="text-gray-600 mb-4">Пока нет записанных встреч</p>
          <Link href="/upload" className="text-blue-600 hover:underline">
            Загрузить первую запись
          </Link>
        </div>
      ) : (
        <div className="space-y-8">
          {Object.entries(groupedMeetings).map(([month, monthMeetings]) => (
            <div key={month}>
              <h2 className="text-lg font-semibold text-gray-700 mb-4 capitalize">
                {month}
              </h2>
              <div className="bg-white rounded-lg shadow-sm border divide-y">
                {monthMeetings.map((meeting) => (
                  <Link
                    key={meeting.id}
                    href={`/meetings/${meeting.id}`}
                    className="flex items-center justify-between p-4 hover:bg-gray-50"
                  >
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center">
                        <User className="text-blue-600" size={24} />
                      </div>
                      <div>
                        <p className="font-medium">{meeting.employees?.name}</p>
                        <p className="text-sm text-gray-500">
                          {new Date(meeting.date).toLocaleDateString('ru-RU', {
                            weekday: 'long',
                            day: 'numeric',
                            month: 'long',
                          })}
                        </p>
                        {meeting.summary && (
                          <p className="text-sm text-gray-600 mt-1 line-clamp-1 max-w-md">
                            {meeting.summary}
                          </p>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      {meeting.mood_score && (
                        <span
                          className={`px-3 py-1 rounded-full text-sm font-medium ${
                            meeting.mood_score >= 7
                              ? 'bg-green-100 text-green-800'
                              : meeting.mood_score >= 5
                              ? 'bg-yellow-100 text-yellow-800'
                              : 'bg-red-100 text-red-800'
                          }`}
                        >
                          {meeting.mood_score}/10
                        </span>
                      )}
                      <ChevronRight className="text-gray-400" size={20} />
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
